### ISSUE TITLE
Corrección en una funcionalidad

### ISSUE THREAD

**Issue by micheldevs** [cs-ehu/GAICurricula#12]
Se podría investigar más XQuery para incorporar en el código de xquery una manera de que la aplicación pueda reconocer todos los datos del pom sin tener que borrar en su etiqueta inicial algo.

**Estimación - 3 horas**

**Comment by UrkoLekuona** [comment]
El _commit_ b93cfb7 soluciona el problema en el que había que eliminar los atributos de la cabecera del POM para que se transformase correctamente a HTML. El problema consistía en que no estaba declarado el _namespace_ que utiliza el POM. Una vez declarado, haciendo referencia a él en todas las sentencias XQuery el programa funciona como se esperaba en un principio.

Además, también se ha solucionado un _bug_ donde no se leía correctamente la información sobre los _plugins_. Esto es porque el programa esperaba que la ruta de los _plugins_ fuese `project/build/pluginManagement/plugins/plugin`, pero el directorio _pluginManagement_ es opcional. Se ha solucionado modificando la ruta a `project/build//plugins/plugin`, que cogerá todos los objetos `plugins/plugin` debajo del directorio `project/build`, sin necesidad de ser hijos directos.

Autores de la correción: [UrkoLekuona](https://github.com/UrkoLekuona) e [igomez137](https://github.com/igomez137)
