### ISSUE TITLE
Aplicación extendida ¿puedes ayudarme con nuevas funcionalidades?

### ISSUE THREAD

**Issue by micheldevs** [cs-ehu/GAICurricula#5]
# Ampliación de la aplicación
La aplicación ya está en su versión **1.0.1** y trae consigo numerosas funcionalidades que se pueden utilizar, bien sea con MAVEN o bien sea en general con su ejecutable. El caso es que depende que casos, sus funcionalidades si tienen campos que pueden ser extendidos y contar con ayuda podría hacer el extender más este proyecto. Entre estas extensiones aquí tengo algunas de las que se me han ido ocurriendo:

* La interfaz gráfica podría ser más cómoda para el usuario dando una ruta por defecto y rellenando aproximadamente los demás campos.
* La interfaz gráfica de la aplicación podría generar el código de consola para mostrar al usuario lo que se realiza.
* La documentación del proyecto se puede extender y en el caso del código hay bastante parte que puede ser refactorizada e incluso se pude mejorar la estructura o el código.
* La interfaz gráfica podría tener un apartado de opciones de estilo para que el HTML que genera la aplicación no sea tan básico, con lo que se podría añadir código CSS.
* La interfaz gráfica podría generar una vista previa de como sería un fichero HTML, puede ser básico, no necesita que sea de los datos del pom que se va a generar.
* Se podría investigar más XQuery para incorporar en el código de xquery una manera de que la aplicación pueda reconocer todos los datos del pom sin tener que borrar en su etiqueta inicial algo.
* El apartado de validaciones puede ser más completo en la interfaz.

Si quieres echarme una mano contacta conmigo y si quieres ver una visión general del proyecto, consulta su [**readme**](https://github.com/cs-ehu/GAICurricula/blob/master/readme.md).

**Comment by jiptohej** [comment]
Me parece genial. Utiliza el término ampliación en lugar de amplificación. Ya hablaremos mañana
